type story={
id_user:string,
id_story:string,
title_main:string,
auther_name:string,
is_complete:boolean;
genre:number;
catch_copy:string,
synopsis:string,
keywords:string,
extreme_depiction:string,
color_type:number;
accept_advertisement:boolean;
accept_rating:boolean;
accept_reviews:boolean;
accept_impression:boolean;
publish_evaluation:boolean;
accept_typo_reports:boolean;
}
