export const selectStory = `query{
  selectStory(id:"00001"){
    id,
  id_story,
  title_main,
  auther_name,
  is_complete,
  genre,
  catch_copy,
  synopsis,
  keywords,
  extreme_depiction,
  color_type,
  accept_advertisement,
  accept_rating,
  accept_reviews,
  accept_impression,
  publish_evaluation,
  accept_typo_reports
  }
}`