<template>
  <span>
    <dl>
      <dt>ジャンル</dt>
      <dd>
        <label>
          <span>異世界ファンタジー</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>現代ファンタジー</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>SF</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>恋愛</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>ラブコメ</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>現代ドラマ</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>ホラー</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>ミステリー</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>エッセイ・ノンフィクション</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>歴史・時代・伝記</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>創作論・評論</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
          <span>詩・童話・その他</span>
          <input
            id="type"
            type="radio"
            name="genre"
            :value="genre"
            @change="formUpdate"
          />
        </label>
      </dd>
    </dl>
  </span>
</template>
<script>
export default {
  props: {
    genre: {
      type: String,
      default: null,
    },
  },
  methods: {
    formUpdate(e) {
      this.$emit("formUpdate", e);
    },
  },
};
</script>
<style lang="scss" scoped></style>
